version: '2'
services:
  grafana:
    build: './config/grafana'
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
  db:
    container_name: db
    image: postgres:alpine
    environment:
      - POSTGRES_DB=conferencemanager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresql
    ports:
    - "5432:5432"
  web:
    build: .
    container_name: web
    ports:
    - "8080:8080"
    environment:
    - "SPRING_PROFILES_ACTIVE=json-logs,docker,actuator"
networks:
  monitoring:
