spring:
  datasource:
    url: jdbc:postgresql://db:5432/conferencemanager
    username: postgres
    password: postgresql
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      pool-name: library-db-cp
    initialization-mode: never
